spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-coupon
  config:
    import:
      - nacos:mall-coupon.properties?refreshEnabled=true&group=DEFAULT_GROUP

mybatis-plus:
  # 配置mapper的位置 , 默认值也是这个
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置ID自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 5100