spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-coupon
  config:
    import:
      - nacos:mall-coupon.properties?refreshEnabled=true&group=DEFAULT_GROUP
  jackson: # 接口返回的JSON里的时间格式处理
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  # 配置mapper的位置 , 默认值也是这个
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置ID自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 5100

# ==================== seata ===========================================
#seata:
#  enabled: true
#  application-id: ${spring.application.name} # 应用 ID，通常与 Spring Boot 应用名称一致
#  tx-service-group: ${spring.application.name}_tx_group # 事务组名称
#
#  service:
#    vgroup-mapping:
#      ${seata.tx-service-group}: default
#    grouplist:
#      default: 127.0.0.1:8091         # Seata Server 地址
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      application: seata-server
#      context-path: /nacos
#      cluster: default
#  data-source-proxy-mode: AT
#  enable-auto-data-source-proxy: false