spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    # =========================== sentinel spring.cloud ===================================
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333 # 控制台地址
        port: 8719 # 传输端口 （8719默认的）
  application:
    name: mall-coupon
  config:
    import:
      - nacos:mall-coupon.properties?refreshEnabled=true&group=DEFAULT_GROUP
  jackson: # 接口返回的JSON里的时间格式处理
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    format: # 只会影响 @RequestParam、@PathVariable 的参数格式 ，不会影响 @RequestBody 反序列化 JSON 时 Date 类型的格式。
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  # 配置mapper的位置 , 默认值也是这个
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置ID自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 5100
#============================ 日志 ====================================
logging:
  level:
    com.vurtnewk.mall: debug
# ==================== seata ===========================================
#seata:
#  enabled: true
#  application-id: ${spring.application.name} # 应用 ID，通常与 Spring Boot 应用名称一致
#  tx-service-group: ${spring.application.name}_tx_group # 事务组名称
#
#  service:
#    vgroup-mapping:
#      ${seata.tx-service-group}: default
#    grouplist:
#      default: 127.0.0.1:8091         # Seata Server 地址
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      application: seata-server
#      context-path: /nacos
#      cluster: default
#  data-source-proxy-mode: AT
#  enable-auto-data-source-proxy: false
#============================ sentinel的统计信息配置 暴露endpoints ====================================
management:
  endpoints:
    web:
      exposure:
        include: "*"
#============================ 开启 feign 的 sentinel 功能 ====================================
feign:
  sentinel:
    enabled: true