spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        server-addr: 127.0.0.1:8848
  # 如果没有名字，nacos里看不到
  application:
    name: mall-search
  thymeleaf:
    cache: false

server:
  port: 5700

logging:
  level:
    com.vurtnewk.mall: debug