spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
   # =========================== redis ===================================
  data:
    redis:
     host: 127.0.0.1
     port: 6379
  # =========================== 名字 ===================================
  application:
    name: mall-seckill
# =========================== 线程池的属性 ===================================
  task:
    execution:
      pool:
        core-size: 20
        max-size: 50
# =========================== 定时任务的线程 ===================================
#  task:
#    scheduling:
#      pool:
#        size: 5

#============================ 端口 ====================================
server:
  port: 6000
#============================ 日志 ====================================
logging:
  level:
    com.vurtnewk.mall: debug