spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
  application:
    name: mall-auth-server
  data:
    redis:
      host: 127.0.0.1
      port: 6379
    # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true # 可防止缓存穿透
  thymeleaf:
    cache: false
#  session:
#    timeout: 10800

server:
  port: 5800
#  servlet:
#    session:
#      timeout: 10800

#============================ sentinel的统计信息配置 暴露endpoints ====================================
management:
  endpoints:
    web:
      exposure:
        include: "*"
#============================ 开启 feign 的 sentinel 功能 ====================================
feign:
  sentinel:
    enabled: true