spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    # =========================== sentinel spring.cloud ===================================
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333 # 控制台地址
        port: 8719 # 传输端口 （8719默认的）
  config:
    import:
      - nacos:third-party.properties?refreshEnabled=true&group=DEFAULT_GROUP

  # 如果没有名字，nacos里看不到
  application:
    name: mall-third-party


server:
  port: 5600
management:
  #============================ zipkin ====================================
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
  #============================ sentinel的统计信息配置 暴露endpoints ====================================
  endpoints:
    web:
      exposure:
        include: "*"
#============================ 开启 feign 的 sentinel 功能 ====================================
feign:
  sentinel:
    enabled: true