spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  # 如果没有名字，nacos里看不到
  application:
    name: mall-order
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true # 发送端消息抵达队列的确认
    template:
      mandatory: true # 只要抵达队列，已异步发送优先回调我们的这个 returnConfirm
    listener:
      simple:
        acknowledge-mode: manual # 消息的收到 改为手动模式
  #    publisher-confirm-type: none # 开销低，性能较好，适用于不需要精确确认的场景。
  #    publisher-confirms: true 新版本中废弃
  thymeleaf:
    cache: true
  jackson: # 接口返回的JSON里的时间格式处理
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
    # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true # 可防止缓存穿透
#      key-prefix: CACHE_   # 前缀：如果制定则使用，没有则默认使用缓存的名字作为前缀
#      use-key-prefix: true 是否开启前缀等


mybatis-plus:
  # 配置mapper的位置 , 默认值也是这个
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置ID自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 5300

mall:
  thread:
    core-size: 10
    max-size: 200
    keep-alive-time: 10