spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  # 如果没有名字，nacos里看不到
  application:
    name: mall-order
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true # 发送端消息抵达队列的确认
    template:
      mandatory: true # 只要抵达队列，已异步发送优先回调我们的这个 returnConfirm
#    publisher-confirm-type: none # 开销低，性能较好，适用于不需要精确确认的场景。
#    publisher-confirms: true 新版本中废弃
mybatis-plus:
  # 配置mapper的位置 , 默认值也是这个
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置ID自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 5300