spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  application:
    name: mall-order  # 如果没有名字，nacos里看不到
  #===================== rabbitmq ============================================
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true # 发送端消息抵达队列的确认
    template:
      mandatory: true # 只要抵达队列，已异步发送优先回调我们的这个 returnConfirm
    listener:
      simple:
        acknowledge-mode: manual # 消息的收到 改为手动模式
  #    publisher-confirm-type: none # 开销低，性能较好，适用于不需要精确确认的场景。
  #    publisher-confirms: true 新版本中废弃
  thymeleaf:
    cache: true
  jackson: # 接口返回的JSON里的时间格式处理
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  cache:   # 缓存配置
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true # 可防止缓存穿透
#      key-prefix: CACHE_   # 前缀：如果制定则使用，没有则默认使用缓存的名字作为前缀
#      use-key-prefix: true 是否开启前缀等

#===================== mybatis ============================================
mybatis-plus:
  # 配置mapper的位置 , 默认值也是这个
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置ID自增
  global-config:
    db-config:
      id-type: auto
#===================== 端口 ============================================
server:
  port: 5300
#===================== 本地自定义线程池 ==================================
mall:
  thread:
    core-size: 10
    max-size: 200
    keep-alive-time: 10
# ==================== seata ===========================================
seata:
  enabled: true
  application-id: ${spring.application.name} # 应用 ID，通常与 Spring Boot 应用名称一致
  tx-service-group: mall-order_tx_group #  Seata 客户端的事务组名称，用于标识当前应用的事务组

  service:
    vgroup-mapping:
      mall-order_tx_group: default #用于将事务组（tx-service-group）映射到 Seata Server 的集群名称。
    grouplist:
      default: 127.0.0.1:8091         # Seata Server 地址
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      application: seata-server
      context-path: /nacos
      cluster: default  #指定 Seata 客户端的集群名称
  data-source-proxy-mode: AT #AT（Auto Transaction）：自动模式，Seata 会自动管理分布式事务
  enable-auto-data-source-proxy: false #指定是否启用 Seata 的自动数据源代理 这里自动会时不时报错